const categories = [
  {
    id: 1,
    name: "Electronics",
    description: "Devices and gadgets for everyday use.",
    imageUrl: "/10-Must-Have-Kitchen-Products.jpg",
    productsCount: 120,
    price: 299.99,
  },
  {
    id: 2,
    name: "Fashion",
    description: "Clothing and accessories for all seasons.",
    imageUrl: "/collection_2.png",
    productsCount: 200,
    price: 79.99,
  },
  {
    id: 3,
    name: "Home & Kitchen",
    description: "Furniture, appliances, and decor.",
    imageUrl: "/collection-outdoor-sports-equipment-kids_1007506-14348.avif",
    productsCount: 85,
    price: 129.99,
  },
  {
    id: 4,
    name: "Books",
    description: "Fiction, non-fiction, and educational materials.",
    imageUrl: "/crowded-toy-store-stockcake.jpg",
    productsCount: 150,
    price: 19.99,
  },
  {
    id: 5,
    name: "Sports & Outdoors",
    description: "Equipment and gear for sports and outdoor activities.",
    imageUrl: "/Darya-Degrowth-Header-1.jpg",
    productsCount: 60,
    price: 159.99,
  },
  {
    id: 6,
    name: "Health & Beauty",
    description: "Wellness and personal care products.",
    imageUrl: "/images.jpeg",
    productsCount: 95,
    price: 49.99,
  },
  {
    id: 7,
    name: "Toys & Games",
    description: "Fun and entertainment for kids and adults.",
    imageUrl: "/next.svg",
    productsCount: 45,
    price: 39.99,
  },
  {
    id: 8,
    name: "Automotive",
    description: "Car parts, accessories, and tools.",
    imageUrl: "/The-art-of-storytelling-in-electronic-product-photography.webp",
    productsCount: 30,
    price: 99.99,
  },
  {
    id: 9,
    name: "Groceries",
    description: "Daily essentials and food products.",
    imageUrl: "/shop-online-slider-template-4f2c60.webp",
    productsCount: 300,
    price: 59.99,
  },
  {
    id: 10,
    name: "Pets",
    description: "Supplies and accessories for your furry friends.",
    imageUrl: "/images.jpeg",
    productsCount: 40,
    price: 25.99,
  },
];

export default categories;
